### ISSUE TITLE
Missing Opus Module

### ISSUE THREAD

**Issue by MittiAlex** [amishshah/prism-media#44] opened 2020-04-10 18:16 UTC
Hello folks,
#### Issue:

I'm trying to program a small discord bot in javascript. The bot is supposed to join in a voice server if someone types "-snus", that works. After that it should play a sound and leave the voice channel again. So i'm a bit familiar with javascript so i coded this little script:

```
const Discord = require('discord.js');
const bot = new Discord.Client();

const token = 'XXXXX';

bot.on('ready', () => {
    console.log("Er is online!!");
});

bot.on('message',async message=>{
    if(message.content === "-snus")
    {
        if(message.member.voice.channel)
        {
            const connection = await message.member.voice.channel.join();
            const ytdl = require('ytdl-core');
            connection.play(ytdl('XXX', { filter: 'audioonly' }));
        }
        else
        {
            message.reply('Geh in an voice channel du kek');
        }
    }
})
bot.login(token);
```

On windows this just works fine i installed a nodejs environment and downloaded via npm discord.js, ytdl-core and opusscript. To make it run 24/7 i want to make it run on a raspberry pi 3b. Again same procedure moved the script to my raspberry downloaded the packages and than this error occures: 

```
Er is online!!
TypeError: Cannot convert "null" to int
TypeError: Cannot convert "null" to int /var/www/dcbots/node_modules/opusscript/build/opusscript_native_wasm.js:8 var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key_
```

and so on i don't think this is important soo fast forward after some googleing i found out that this is due to the opusscript packet, it shouldn't be used for discord voice bots so I uninstalled it and than this error pops out: 

_(node:24615) UnhandledPromiseRejectionWarning: Error: Could not find an Opus module! Please install @discordjs/opus, node-opus, or opusscript._

Ok so this and basically everyone else on the internet tells me to install @discordjs/opus and it 
seems to work for everyone expect me. When I try to install this via npm i get this error message:
so i type $npm install @discordjs/opus 

```
@discordjs/opus@0.1.0 install /var/www/dcbots/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.1.0 and node@13.11.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/var/www/dcbots/node_modules/@discordjs/opus/prebuild' 
gyp WARN EACCES current user ("Alexander") does not have permission to access the dev dir "/root/.cache/node-gyp/13.11.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/dcbots/node_modules/@discordjs/opus/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/dcbots/node_modules/@discordjs/opus/.node-gyp'
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/www/dcbots/node_modules/@discordjs/opus/prebuild/node-v79-linux-arm/opus.node" "--module_name=opus" "--module_path=/var/www/dcbots/node_modules/@discordjs/opus/prebuild/node-v79-linux-arm" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /var/www/dcbots/node_modules/@discordjs/opus
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/nodejs/bin/node /opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/dcbots/node_modules/@discordjs/opus/prebuild/node-v79-linux-arm/opus.node --module_name=opus --module_path=/var/www/dcbots/node_modules/@discordjs/opus/prebuild/node-v79-linux-arm --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/dcbots/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.97-v7+
node-pre-gyp ERR! command "/opt/nodejs/bin/node" "/var/www/dcbots/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/dcbots/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v13.11.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
Failed to execute '/opt/nodejs/bin/node /opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/var/www/dcbots/node_modules/@discordjs/opus/prebuild/node-v79-linux-arm/opus.node --module_name=opus --module_path=/var/www/dcbots/node_modules/@discordjs/opus/prebuild/node-v79-linux-arm --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm WARN dcbots@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     _/root/.npm/_logs/2020-04-10T17_56_40_347Z-debug.log
```

I'm not getting much wiser with these logs either. So bacically my probleam is that i am unable to install the @discordjs/opus module for my raspberry.
I don't get why I can't install this module is it just for windows?
#### Steps to reproduce:

try to install @discordjs/opus on linux

#### Further details:
- Operating System:

- PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
- NAME="Raspbian GNU/Linux"
- VERSION_ID="10"
- VERSION="10 (buster)"
- VERSION_CODENAME=buster
- ID=raspbian
- ID_LIKE=debian

- Node.js version: v13.11.0
  npm: '6.14.4',
- Commit I'm using:

**Comment by smartclash** [comment] 2020-07-13 15:18
Possible duplicate of https://github.com/amishshah/prism-media/issues/30

**Comment by amishshah** [comment] 2020-07-13 15:47
This is an issue for [@discordjs/opus](https://github.com/discordjs/opus)

**Closed by amishshah** 2020-07-13 15:47 UTC
